# -*- coding: utf-8 -*-
"""C209_ATML_LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCngtIl36JaBNRsAJZdC_t8h14wazqxj
"""

import sys
sys.path.append('/content/drive/MyDrive/SNN-TL-Data')

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import timm

import torch.nn.functional as F
from torch import nn
from torch.utils.data import Dataset, DataLoader

from skimage import io
from sklearn.model_selection import train_test_split

from tqdm import tqdm

DATA_DIR = '/content/drive/MyDrive/SNN-TL-Data/train'
CSV_FILE = '/content/drive/MyDrive/SNN-TL-Data/train.csv'

BATCH_SIZE = 32
LR = 0.001
EPOCHS = 1

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

df = pd.read_csv(CSV_FILE)
df.head()

class APN_Dataset(Dataset):
  def __init__(self,df):
    self.df = df
  def __len__(self):
    return len(self.df)
  def __getitem__(self, index):
    row = self.df.iloc[index]

    A_img = io.imread(DATA_DIR + '/' + row.Anchor)
    P_img = io.imread(DATA_DIR + '/' + row.Positive)
    N_img = io.imread(DATA_DIR + '/' + row.Negative)

    A_img = torch.from_numpy(A_img).permute(2, 0, 1)/255
    P_img = torch.from_numpy(P_img).permute(2, 0, 1)/255
    N_img = torch.from_numpy(N_img).permute(2, 0, 1)/255

    return A_img, P_img, N_img

train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

trainset = APN_Dataset(train_df)
valset = APN_Dataset(val_df)

idx = 1
A, P, N = trainset[idx]

f, (ax1,ax2,ax3) = plt.subplots(1,3, figsize=(10,5))
ax1.set_title('Anchor')
ax1.imshow(A.permute(1,2,0), cmap= 'gray')
ax2.set_title('Positive')
ax2.imshow(P.permute(1,2,0), cmap= 'gray')
ax3.set_title('Negative')
ax3.imshow(N.permute(1,2,0), cmap= 'gray')

train_loader = DataLoader(trainset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(valset, batch_size=BATCH_SIZE)

print(f"No. of batches in trainloader: {len(train_loader)}")
print(f"No. of batches in valloader: {len(val_loader)}")

class APN_Model(nn.Module):

    def __init__(self, emb_size=512):
        super(APN_Model, self).__init__()

        self.efficientnet = timm.create_model('efficientnet_b0', pretrained=True)

        self.efficientnet.classifier = nn.Linear(in_features=self.efficientnet.classifier.in_features, out_features=emb_size)

    def forward(self, images):
        embeddings = self.efficientnet(images)
        return embeddings

model = APN_Model()
model.to(DEVICE);

def train_fn(model, dataloader, optimizer, criterion):
    model.train()
    total_loss = 0.0

    for A, P, N in tqdm(dataloader):
        A, P, N = A.to(DEVICE), P.to(DEVICE), N.to(DEVICE)

        A_embs = model(A)
        P_embs = model(P)
        N_embs = model(N)

        loss = criterion(A_embs, P_embs, N_embs)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(dataloader)

def eval_fn(model, dataloader, criterion):

    model.eval()
    total_loss = 0.0

    with torch.no_grad():
        for A, P, N in tqdm(dataloader):

            A, P, N = A.to(DEVICE), P.to(DEVICE), N.to(DEVICE)

            A_embs = model(A)
            P_embs = model(P)
            N_embs = model(N)

            loss = criterion(A_embs, P_embs, N_embs)

            total_loss += loss.item()

    return total_loss / len(dataloader)

criterion = nn.TripletMarginLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

best_valid_loss = np.inf

for i in range(EPOCHS):

    train_loss = train_fn(model, train_loader, optimizer, criterion)
    valid_loss = eval_fn(model, val_loader, criterion)

    if valid_loss < best_valid_loss:
        torch.save(model.state_dict(), 'best_model.pt')
        best_valid_loss = valid_loss
        print('SAVED_WEIGHTS_SUCCESS')

    print(
        f"EPOCHS : {i+1} "
        f"train_loss : {train_loss} "
        f"valid_loss : {valid_loss}"
    )

def get_encoding_csv(model, anc_img_names):
    anc_img_names_arr = np.array(anc_img_names)
    encodings = []

    model.eval()

    with torch.no_grad():
        for i in tqdm(anc_img_names_arr):
            A = io.imread(DATA_DIR + '/' + i)
            A = torch.from_numpy(A).permute(2, 0, 1) / 255.0
            A = A.to(DEVICE)

            # (C, H, W) -> (1, C, H, W)
            A_enc = model(A.unsqueeze(0))

            encodings.append(
                A_enc.squeeze().cpu().detach().numpy()
            )

    encodings = np.array(encodings)
    encodings = pd.DataFrame(encodings)

    df_enc = pd.concat(
        [anc_img_names.reset_index(drop=True), encodings],
        axis=1
    )

    return df_enc

model.load_state_dict(torch.load('best_model.pt'))

df_enc = get_encoding_csv(model, df['Anchor'])

df_enc.to_csv('database.csv', index = False)

df_enc.head()

def euclidean_dist(img_enc, anc_enc_arr):
  dist = np.sqrt(
      np.dot(img_enc - anc_enc_arr, (img_enc - anc_enc_arr).T)
  )
  return dist

idx = 0
img_name = df_enc['Anchor'].iloc[idx]
img_path = DATA_DIR + '/' + img_name

img = io.imread(img_path)
img = torch.from_numpy(img).permute(2, 0, 1)/255.0

model.eval()
with torch.no_grad():
  img = img.to(DEVICE)
  img_enc = model(img.unsqueeze(0))
  img_enc = img_enc.squeeze().cpu().detach().numpy()
  anc_enc_arr = df_enc.iloc[:,1:].to_numpy()
  anc_img_names = df_enc['Anchor']

from IPython.core.interactiveshell import dis
distance = []

for i in range(anc_enc_arr.shape[0]):
  dist = euclidean_dist(img_enc, anc_enc_arr[i:i+1,:])
  distance = np.append(distance, dist)

closest_idx = np.argsort(distance)
from utils1 import plot_closest_imgs
plot_closest_imgs(anc_img_names, DATA_DIR, img, img_path, closest_idx, distance, no_of_closest = 5);

