# -*- coding: utf-8 -*-
"""Utils1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hgm44ltvntt_dPOrPF6j2Zv1LCtk2aRh
"""

import os
import networkx as nx
from skimage import io
import matplotlib.pyplot as plt

def plot_closest_imgs(
    anc_img_names,
    DATA_DIR,
    image,
    img_path,
    closest_idx,
    distance,
    no_of_closest=10
):

    G = nx.Graph()

    # Query image name
    S_name = [os.path.basename(img_path)]

    # Add closest image names
    for s in range(no_of_closest):
        S_name.append(anc_img_names.iloc[closest_idx[s]])

    # Add nodes with images
    for i in range(len(S_name)):
        img_full_path = os.path.join(DATA_DIR, S_name[i])
        img_data = io.imread(img_full_path)
        G.add_node(i, image=img_data)

    # Add edges with distances
    for j in range(1, no_of_closest + 1):
        G.add_edge(0, j, weight=distance[closest_idx[j - 1]])

    # Graph layout
    pos = nx.kamada_kawai_layout(G)

    fig = plt.figure(figsize=(20, 20))
    ax = plt.subplot(111)
    ax.set_aspect('equal')

    nx.draw_networkx_edges(G, pos, ax=ax)

    plt.xlim(-1.5, 1.5)
    plt.ylim(-1.5, 1.5)

    trans = ax.transData.transform
    trans2 = fig.transFigure.inverted().transform

    piesize = 0.1
    p2 = piesize / 2.0

    for n in G:
        xx, yy = trans(pos[n])
        xa, ya = trans2((xx, yy))
        a = plt.axes([xa - p2, ya - p2, piesize, piesize])
        a.set_aspect('equal')
        a.imshow(G.nodes[n]['image'])
        a.set_title(S_name[n][:4])
        a.axis('off')

    ax.axis('off')
    plt.show()